parameters:
    baseurl: 'http://localhost/'
    deezer: { apikey: frw9H5NeqioSk43A1zy00AY9PpAJjnXo494YPtsMfhWaVf5CH0i, secret: b29929f075480ff3aabaceb34d9154ab, appid: 594344 }
    lastfm: { username: aeeon3, subscriber: '0', apiKey: 60d016e2508779089b4bd053b9645715, apiSecret: 15d9771f3542a5301ad9b27af3a68994, sessionKey: mlU25LTNdC3pA6p5VEyhrgksCWR5uUMZ }
    listenbrainz: { token: 11614abe-3472-48c8-8e2a-88724b8f342a, username: aeeon }
services:
    _defaults: { autowire: true, autoconfigure: true }
    App\: { resource: ../src/, exclude: [../src/DependencyInjection/, ../src/Entity/, ../src/Kernel.php] }
