<?php

namespace ContainerE87eQWs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLastfmControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\LastfmController' shared autowired service.
     *
     * @return \App\Controller\LastfmController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/LastfmController.php';

        $container->services['App\\Controller\\LastfmController'] = $instance = new \App\Controller\LastfmController(($container->services['App\\Controller\\DeezerController'] ?? $container->load('getDeezerControllerService')), ($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\LastfmController', $container));

        return $instance;
    }
}
