parameters:
    baseurl: 'http://localhost/'
    deezer: { apikey: frw9H5NeqioSk43A1zy00AY9PpAJjnXo494YPtsMfhWaVf5CH0i, secret: b29929f075480ff3aabaceb34d9154ab, appid: '594344' }
    lastfm: { username: aeeon3, subscriber: '0', apiKey: 60d016e2508779089b4bd053b9645715, apiSecret: 15d9771f3542a5301ad9b27af3a68994, sessionKey: eu2V5e_0zS2DHSh3pX8rBDy8hQeTMPsD }
    listenbrainz: { username: aeeon, token: 4d549e5a-fd4a-4f42-812d-63d48a6c55bf }
services:
    _defaults: { autowire: true, autoconfigure: true }
    App\: { resource: ../src/, exclude: [../src/DependencyInjection/, ../src/Entity/, ../src/Kernel.php] }
