<?php

namespace ContainerEhTFhIU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackApiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6HIe2Fp.LastFmApi\Api\TrackApi' shared service.
     *
     * @return \LastFmApi\Api\TrackApi
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6HIe2Fp": it references class "LastFmApi\\Api\\TrackApi" but no such service exists.');
    }
}
