<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYsodfry\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYsodfry/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYsodfry.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYsodfry\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYsodfry\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ysodfry',
    'container.build_id' => 'c5a3bc86',
    'container.build_time' => 1697716457,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYsodfry');
