<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVtDtyUr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVtDtyUr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVtDtyUr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVtDtyUr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVtDtyUr\App_KernelDevDebugContainer([
    'container.build_hash' => 'VtDtyUr',
    'container.build_id' => '2f424995',
    'container.build_time' => 1698070292,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVtDtyUr');
