<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQG5BKot\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQG5BKot/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQG5BKot.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQG5BKot\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQG5BKot\App_KernelDevDebugContainer([
    'container.build_hash' => 'QG5BKot',
    'container.build_id' => '50dabb08',
    'container.build_time' => 1697734226,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQG5BKot');
