<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'deezer_connect' => [[], ['_controller' => 'App\\Controller\\DeezerController::index'], [], [['text', '/deezer/connect']], [], [], []],
    'deezer_load' => [[], ['_controller' => 'App\\Controller\\DeezerController::loadAlbum'], [], [['text', '/deezer/load']], [], [], []],
    'deezer_logout' => [[], ['_controller' => 'App\\Controller\\DeezerController::logout'], [], [['text', '/deezer/logout']], [], [], []],
    'deezer_history' => [[], ['_controller' => 'App\\Controller\\DeezerController::getUserHistory'], [], [['text', '/deezer/history']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'lastfm_connect' => [[], ['_controller' => 'App\\Controller\\LastfmController::connect'], [], [['text', '/lastfm/connect']], [], [], []],
    'lastfm_scrobble' => [[], ['_controller' => 'App\\Controller\\LastfmController::scrobble'], [], [['text', '/lastfm/scrobble']], [], [], []],
    'lastfm_recent' => [[], ['_controller' => 'App\\Controller\\LastfmController::recent'], [], [['text', '/lastfm/recent']], [], [], []],
];
